# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: 'Junit'
    displayName: 'Junit Stage'
    jobs:
      - job: 'JunitTest'
        displayName: 'Running Junit tests'
        steps:
          - script: echo 'Running demo app unit test'
          - task: CopyFiles@2
            displayName: Copy Files
            inputs:
              SourceFolder: $(system.defaultworkingdirectory)/target/azure-functions/
              Contents: '**'
              TargetFolder: $(build.artifactstagingdirectory)
          - task: Maven@3
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'Test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              codeCoverageToolOption: 'JaCoCo'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
              checkStyleRunAnalysis: true
              pmdRunAnalysis: true
